FROM node:12.10.0-alpine
WORKDIR /app/letvote-backend
COPY ./package.json ./package.json
RUN apk add --no-cache make gcc g++ python  
RUN npm install 
RUN npm install -g sequelize-cli --unsafe-perm
RUN npm install -g sqlite3@4.1.0 --unsafe-perm
RUN npm install -g pkg@4.4.0 --unsafe-perm
RUN mv node_modules /app
ENTRYPOINT ["sh", "-c", "cp -r ../node_modules/ ."]
EXPOSE 3000
